#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  16
yabai -m config bottom_padding               16
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   12

# status bar spacing
yabai -m config external_bar main:20:0

# do not manage these apps
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --all app="^Cisco AnyConnect Secure Mobility Client$" manage=off
yabai -m rule --all app="^Zscaler$" manage=off
yabai -m rule --all app="^Archive Utility$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^VLC$" manage=off

# simplebar config
echo "yabai configuration loaded.."

# Refresh spaces widget on space change
yabai -m signal --add event=space_changed \
  action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=space_changed \
  action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
yabai -m signal --add event=window_title_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
yabai -m signal --add event=application_activated \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
yabai -m signal --add event=application_front_switched \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
yabai -m signal --add event=application_front_switched \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=application_launched \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=application_terminated \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=window_destroyed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
